apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: app1
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
        - app.kelasdevops.xyz
      secretName: app-tls
  rules:
    - host: app.kelasdevops.xyz
      http:
        paths:
          - backend:
              serviceName: app
              servicePort: 80
