apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: app1
spec:
  rules:
    - host: app.kelasdevops.xyz
      http:
        paths:
          - backend:
              serviceName: app
              servicePort: 80
