version: "3"

services:
  app:
    image: agung3wi/php7.4-apache
    container_name: app
    links:
      - "mysql:mysql"
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: bootcamp
      DB_USERNAME: bootcamp
      DB_PASSWORD: bootcamp
    volumes:
      - "../laravel:/app"
    ports:
      - "8000:80"
  migrate:
    image: agung3wi/php7.4-apache
    container_name: migrate
    links:
      - "mysql:mysql"
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: bootcamp
      DB_USERNAME: bootcamp
      DB_PASSWORD: bootcamp
    volumes:
      - "../laravel:/app"
    command: php artisan migrate
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: bootcamp
      MYSQL_DATABASE: bootcamp
      MYSQL_USER: bootcamp
      MYSQL_PASSWORD: bootcamp
    ports:
      - "3307:3306"
    restart: always

  minio:
    image: quay.io/minio/minio:RELEASE.2022-01-08T03-11-54Z
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  redis:
    image: "redis:alpine"
    command: redis-server --requirepass sOmE_sEcUrE_pAsS
    ports:
      - "6379:6379"
    environment:
      - REDIS_REPLICATION_MODE=master
