version: "3"

services:
  app:
    image: agungdevops/laravel:v1
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: bootcamp
      DB_USERNAME: bootcamp
      DB_PASSWORD: bootcamp
      SESSION_DRIVER: redis
      REDIS_HOST: redis
      REDIS_PASSWORD: sOmE_sEcUrE_pAsS
      REDIS_PORT: 6379
      FILESYSTEM_DRIVER: minio
      MINIO_KEY: minio1234
      MINIO_SECRET: minio1234
      MINIO_BUCKET: bootcamp
      MINIO_ENDPOINT: http://minio:9000
    ports:
      - "80:80"
