version: "3"

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: bootcamp
      MYSQL_DATABASE: bootcamp
      MYSQL_USER: bootcamp
      MYSQL_PASSWORD: bootcamp
    ports:
      - "3307:3306"
    restart: always
    volumes:
      - ./datamysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 1000M
    restart: always
    ports:
      - 9900:80
volumes:
  mysql:
