apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f laravel.yml
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: app
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: app
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f laravel.yml
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: app
    spec:
      containers:
        - env:
            - name: DB_CONNECTION
              value: mysql
            - name: DB_DATABASE
              value: bootcamp
            - name: DB_HOST
              value: mysql
            - name: DB_PASSWORD
              value: bootcamp
            - name: DB_PORT
              value: "3307"
            - name: DB_USERNAME
              value: bootcamp
            - name: FILESYSTEM_DRIVER
              value: minio
            - name: MINIO_BUCKET
              value: bootcamp
            - name: MINIO_ENDPOINT
              value: http://minio:9000
            - name: MINIO_KEY
              value: minio1234
            - name: MINIO_SECRET
              value: minio1234
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PASSWORD
              value: sOmE_sEcUrE_pAsS
            - name: REDIS_PORT
              value: "6379"
            - name: SESSION_DRIVER
              value: redis
            - name: ELASTIC_APM_SERVER_URL
              value: "http://108.136.248.212:8200"
            - name: ELASTIC_APM_SERVICE_NAME
              value: "AppKelasDevops"
          image: agungdevops/laravel-devops
          imagePullPolicy: Always
          name: app
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m
      restartPolicy: Always
status: {}
