version: '3.4'
services:
  mariadb:
    image: mariadb
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: passw0rd
    restart: always
    volumes:
    - '/data/mysql:/var/lib/mysql'