---
- hosts: app 
  become: true
  vars:
    domain: ansible.kelasdevops.xyz
    email: agungskripsi05@gmail.com
  tasks:
    - name: Create and Install Cert Using nginx Plugin
      command: "certbot --nginx -d  {{ domain }} -m {{ email }} --agree-tos --noninteractive --redirect"